### ISSUE TITLE
Circular import error

### ISSUE THREAD

**Issue by fluffynukeit** [MDSplus/mdsConnector#4]
Installed with pip.

```
>>> from mdsconnector import mdsConnector
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dan/.local/lib/python3.8/site-packages/mdsconnector/__init__.py", line 9, in <module>
    mdsConnector=_import('mdsconnector').mdsConnector
AttributeError: partially initialized module 'mdsconnector' has no attribute 'mdsConnector' (most likely due to a circular import)
```

**Comment by joshStillerman** [comment]
Please try installing the latest version (1.8.0) or possibly (1.8.1).  This has updates to the versions of the dependencies.  Let us know if you have further trouble.

-Josh
